#!/bin/bash

export PACKAGE_CORE_NAME="create-dmg"
export PACKAGE_CORE_BIN_NAME="$PACKAGE_CORE_NAME"
export PACKAGE_CORE_VERSION=v6.0.0
export PACKAGE_CORE_ORG="sindresorhus"

# export PACKAGE_CORE_RELEASE_DOWNLOAD=${PACKAGE_CORE_RELEASE_DOWNLOAD:-"https://github.com/${PACKAGE_CORE_ORG}/create-dmg/releases/download"}
export PACKAGE_CORE_RELEASE_DOWNLOAD="https://github.com/${PACKAGE_CORE_ORG}/create-dmg/releases/download"
